//
//  PersonDetailSceneInteractor.swift
//  MovieDB
//
//  Created by Tolga Taş on 20.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PersonDetailSceneBusinessLogic {
    func getPersonDetail(personId: Int)
}

protocol PersonDetailSceneDataStore {
    //var name: String { get set }
}

class PersonDetailSceneInteractor: PersonDetailSceneBusinessLogic, PersonDetailSceneDataStore {
    var presenter: PersonDetailScenePresentationLogic?
    var worker: PersonDetailSceneWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getPersonDetail(personId: Int) {
        worker = PersonDetailSceneWorker()
        worker?.getPersonDetail(personId: personId).done { result in
            var response = PersonDetailScene.Something.Response(personDetail: result, credits: nil, message: nil)
            
            self.worker?.getPersonCredits(personId: personId).done { result in
                response.credits = result.cast
                self.presenter?.presentPersonDetail(response: response)
            }.catch { error in
                let response = PersonDetailScene.Something.Response(personDetail: nil, credits: nil, message: error.localizedDescription)
                self.presenter?.presentPersonDetail(response: response)
            }
        }.catch{ error in
            let response = PersonDetailScene.Something.Response(personDetail: nil, credits: nil, message: error.localizedDescription)
            self.presenter?.presentPersonDetail(response: response)
        }
    }
}
