//
//  PersonDetailScenePresenter.swift
//  MovieDB
//
//  Created by Tolga Taş on 20.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PersonDetailScenePresentationLogic {
    func presentPersonDetail(response: PersonDetailScene.Something.Response)
}

class PersonDetailScenePresenter: PersonDetailScenePresentationLogic {
    weak var viewController: PersonDetailSceneDisplayLogic?
  
    // MARK: Do something
  
    func presentPersonDetail(response: PersonDetailScene.Something.Response) {
        let viewModel = PersonDetailScene.Something.ViewModel(personDetail: response.personDetail, credits: response.credits)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
