//
//  SearchSceneViewController.swift
//  MovieDB
//
//  Created by Tolga Taş on 19.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift

protocol SearchSceneMoviesDisplayLogic: class {
    func displayMovies(viewModel: SearchScene.Movies.ViewModel)
}

class SearchSceneMoviesViewController: UIViewController, SearchSceneMoviesDisplayLogic {
    var interactor: SearchSceneBusinessLogic?
    var router: (NSObjectProtocol & SearchSceneRoutingLogic & SearchSceneDataPassing)?
    
    var moviesPage: Int = 0
    var moviesSearchPage: Int = 0
    var searchText: String = ""
    var isSearchActive: Bool = false
    
    var movies = [MovieMDB]() {
        didSet {
            tableView.reloadData()
        }
    }
    let tableView = UITableView()
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = SearchSceneInteractor()
        let presenter = SearchScenePresenter()
        let router = SearchSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.moviesViewController = viewController
        router.moviesViewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.backgroundColor = UIColor.yellow
        setupTableView()
        discoverMovies()
    }
    
    // MARK: - Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    private func setupTableView() {
        view.addSubview(tableView)
        tableView.translatesAutoresizingMaskIntoConstraints = false
        tableView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        tableView.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        tableView.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
        
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
        
        tableView.separatorStyle = .none
        tableView.delegate = self
        tableView.dataSource = self
    }
    
    private func discoverMovies() {
        if searchText.isEmpty {
            self.view.showLoading()
            moviesPage = moviesPage + 1
            interactor?.discoverMovies(page: moviesPage)
        }
    }
    
    private func searchMovies(query: String) {
        self.view.showLoading()
        movies.removeAll()
        moviesSearchPage = moviesSearchPage + 1
        interactor?.searchMovies(text: query, page: moviesSearchPage)
    }
    
    func displayMovies(viewModel: SearchScene.Movies.ViewModel) {
        guard let movies = viewModel.movies else {
            let alert = UIAlertController(title: "Error", message: "An error occured.", preferredStyle: UIAlertController.Style.alert)
            alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return
        }
        self.isSearchActive = false
        self.view.stopLoading()
        self.movies.append(contentsOf: movies)
    }
}

// MARK: - TableView Extension

extension SearchSceneMoviesViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return movies.count == 0 ? 1 : movies.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.row == movies.count - 2 {
            if movies.count == moviesSearchPage * 20 || movies.count == moviesPage * 20 {
                searchText.isEmpty ? discoverMovies() : searchMovies(query: searchText)
            }
        }
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        cell.selectionStyle = .none
        
        if isSearchActive {
            cell.textLabel?.text = "Searching..."
            cell.textLabel?.textAlignment = .center
            return cell
        }
        
        if movies.isEmpty {
            cell.textLabel?.text = "0 Movies Found"
            cell.textLabel?.textAlignment = .center
            tableView.separatorStyle = .none
            return cell
        }
        
        cell.textLabel?.text = movies[indexPath.row].title
        cell.textLabel?.textAlignment = .left
        tableView.separatorStyle = .singleLine
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 35
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        
        let myLabel = UILabel()
        myLabel.frame = CGRect(x: 8, y: 0, width: tableView.frame.width, height: 35)
        myLabel.font = UIFont.boldSystemFont(ofSize: 18)
        myLabel.text = "Movies"
        
        let headerView = UIView()
        headerView.backgroundColor = .lightGray
        headerView.addSubview(myLabel)
        
        return headerView
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let movie = movies[indexPath.row]
        
        let movieDetail = MovieDetailSceneViewController()
        movieDetail.movieId = movie.id
        
        self.navigationController?.pushViewController(movieDetail, animated: true)
    }
}

// MARK: - Search Extension
extension SearchSceneMoviesViewController: SearchBarObserver {
    
    func searchCanceled() {
        isSearchActive = true
        searchText.removeAll()
        movies.removeAll()
        moviesPage = 0
        moviesSearchPage = 0
        discoverMovies()
    }
    
    func searchButtonClicked(text: String) {
        searchText = text
        if !text.isEmpty {
            isSearchActive = true
            moviesSearchPage = 0
            searchMovies(query: text)
        }
    }
}
