//
//  SearchSceneModels.swift
//  MovieDB
//
//  Created by Tolga Taş on 19.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift

enum SearchScene {
    // MARK: Use cases
  
    enum Movies {
        struct Request {}
        struct Response {
            var movies: [MovieMDB]?
            var message: String?
        }
        struct ViewModel {
            var movies: [MovieMDB]?
        }
    }
    
    enum People {
        struct Request {}
        struct Response {
            var people: [PersonResults]?
            var message: String?
        }
        struct ViewModel {
            var people: [PersonResults]?
        }
    }
    
    enum Genres {
        struct Request {}
        struct Response {
            var genres: [GenresMDB]?
            var message: String?
        }
        struct ViewModel {
            var genres: [GenresMDB]?
        }
    }
}
