//
//  SearchSceneRouter.swift
//  MovieDB
//
//  Created by Tolga Taş on 19.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchSceneRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SearchSceneDataPassing {
    var dataStore: SearchSceneDataStore? { get }
}

class SearchSceneRouter: NSObject, SearchSceneRoutingLogic, SearchSceneDataPassing {
    weak var moviesViewController: SearchSceneMoviesViewController?
    weak var peopleViewController: SearchScenePeopleViewController?
    weak var genresViewController: SearchSceneGenresViewController?
    var dataStore: SearchSceneDataStore?
  
    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: SearchSceneViewController, destination: SomewhereViewController) {
    //
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: SearchSceneDataStore, destination: inout SomewhereDataStore) {
    //
    //  destination.name = source.name
    //}
}
