//
//  MovieDetailSceneInteractor.swift
//  MovieDB
//
//  Created by Tolga Taş on 20.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailSceneBusinessLogic {
    func getMovieDetail(movieId: Int)
}

protocol MovieDetailSceneDataStore {
    //var name: String { get set }
}

class MovieDetailSceneInteractor: MovieDetailSceneBusinessLogic, MovieDetailSceneDataStore {
    var presenter: MovieDetailScenePresentationLogic?
    var worker: MovieDetailSceneWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getMovieDetail(movieId: Int) {
        worker = MovieDetailSceneWorker()
        worker?.getMovieDetail(movieId: movieId).done { result in
            var response = MovieDetailScene.Something.Response(movieDetail: result, credits: nil, message: nil)
            
            self.worker?.getCredits(movieId: movieId).done { credits in
                response.credits = credits
                self.presenter?.presentMovieDetail(response: response)
            }.catch { error in
                let response = MovieDetailScene.Something.Response(movieDetail: nil, credits: nil, message: error.localizedDescription)
                self.presenter?.presentMovieDetail(response: response)
            }
        }.catch { error in
            let response = MovieDetailScene.Something.Response(movieDetail: nil, credits: nil, message: error.localizedDescription)
            self.presenter?.presentMovieDetail(response: response)
        }
    }
}
