//
//  MovieDetailSceneWorker.swift
//  MovieDB
//
//  Created by Tolga Taş on 20.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift
import PromiseKit

class MovieDetailSceneWorker {
    
    func getMovieDetail(movieId: Int) -> Promise<MovieDetailedMDB> {
        return Promise { seal in
            MovieMDB.movie(movieID: movieId) { (result, movie) in
                guard let movie = movie else {
                    if let error = result.error {
                        seal.reject(error)
                    }
                    return
                }
                seal.fulfill(movie)
            }
        }
    }
    
    func getCredits(movieId: Int) -> Promise<MovieCreditsMDB> {
        return Promise { seal in
            MovieMDB.credits(movieID: movieId) { (result, credits) in
                guard let credits = credits else {
                    if let error = result.error {
                        seal.reject(error)
                    }
                    return
                }
                seal.fulfill(credits)
            }
        }
    }
}
